Techblog/Techblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.views.generic import TemplateView

urlpatterns = [
    
    path('admin/', admin.site.urls),
    url('',include('blog.urls')),
    url('bot/',include('bot.urls')),
    path('accounts/', include('allauth.urls')),
    path('editor/', include('editor.urls')),
    path('ide/',include('ide.urls')),

    #for password reset if some non-solvable error comes
    #url(r'^', include('django.contrib.auth.urls')),
    
]

Techblog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from blog import views
from .views import PRView, PRDone, PRConfirm, PRComplete


app_name = 'blog'
urlpatterns = [

    url(r'^$', views.IndexView, name='index_view'),

    # user
    path('home/profile/<str:username>/',
         views.ProfileView.as_view(), name="profile_view"),
    path('home/blog/<str:username>/', views.BlogView.as_view(), name="blog_view"),
    path('home/profile/<str:username>/edit/',
         views.ProfileEditView.as_view(), name='profile_edit_view'),

    url(r'^contact/', views.contact, name="contact"),
    url(r'^about/', views.about, name="about"),

    url(r'^createblog/', views.createBlog, name="createblog"),

    # for signin/signout
    path('signout/', views.Signout, name='signout'),
    url('signin/', views.Signin, name='signin'),
    # url(r'^register/',views.register,name="register"),
    # url(r'^login/',views.login,name="login"),

    # for email confirmation
    path('signup/', views.signup, name='signup'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),

    # password reset
    path('password/reset/', PRView.as_view(), name='password_reset'),
    path('password/reset/confirm/<uidb64>/<token>',PRConfirm.as_view(), name='password_reset_confirm'),
    path('password/reset/done/',  PRDone.as_view(), name='password_reset_done'),
    path('password/reset/complete/', PRComplete.as_view(),name='password_reset_complete'),

    #editor

]

Techblog/bot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('bot/',views.BotView,name='bot_view')
]

Techblog/ide/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'ide'
urlpatterns = [
    path('geekIDE/',views.Ide,name='ideurl'),
    url(r'^run/$', views.runCode, name='run'), 
      
]

Techblog/blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


# Create your models here.

class Contact(models.Model):
    Name = models.CharField(max_length=200)
    Email = models.EmailField(max_length=200)
    ContactNo= models.PositiveBigIntegerField()
    Message = models.CharField(max_length=500)

    def __str__(self):
        return self.name
    
class User(AbstractUser):
    picture_url = models.CharField(max_length=100,null=True, blank=True)
    full_name = models.CharField(max_length=100, help_text='Help people discover your account by using the name',null=True)
    email = models.EmailField(unique=True)
    
    # last_name=None
    # first_name=None

    # Optional fields
    status = models.CharField(max_length=100,null=True,blank=True,help_text='Help people discover your account by using the name')
    college = models.CharField(max_length=30,blank=True,null=True)
    website = models.CharField(max_length=30,blank=True,null=True)
    country = models.CharField(max_length=20,blank=True,null=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    gender = models.CharField(max_length=10,null=True, blank=True)
    
    def str(self):
        return self.username

Techblog/bot/views.py
from django.shortcuts import render

# Create your views here.
def BotView(request):
    return render(request,'bot/chatroom.html')

Techblog/templates/authentication/auth_blog.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}

<link href="{% static 'img/user-profile-avtr-2.png' %}" rel="icon" />
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}">
<title> Home | {{ request.user.username }} </title>
<style>
    #user__avatar img {
        height: 26px;
        width: 26px;
    }

    .navbar-nav .dropdown-menu {
        position: absolute !important;
    }

    .nav__icons {
        font-size: 24px;
    }

    .signout__btn {
        border: none;
        background: none;
        cursor: pointer;
        padding: 0;
        text-decoration: none;
    }

    .container a {
        text-decoration: none;
        padding: 10px;
    }

    header {
        box-shadow: 0 0 3px 0.5px black;
        background-color: rgba(248, 35, 35, 0.789);
    }

    .searchspace {
        border: none;
        font-size: medium;
        width: 110px;
        height: 25px;
        padding: 10px;
        margin: 10px;
        background-color: rgba(248, 35, 35, 0.789);
        color: white;
        border-bottom: 2px solid white;
        outline: none;
    }

    .name {
        margin-top: 2rem;
        margin-left: 1.5rem;
        text-align: center;
    }

    a {
        text-decoration: none;
    }

    .container-userimage {
        position: relative;
        width: 50%;
        max-width: 300px;
        left: 38%;
    }

    .image {
        display: block;
        width: 50%;
        height: auto;
        border: 1px solid black;
        border-radius: 100%;
    }

    .detail-container {

        display: flex;
        width: 80vw;
        box-shadow: 0 0 5px 3px black;
        margin-top: -55px;
        margin-left: 10vw;
        flex-direction: column;
        border-radius: 20px;
        padding-top: 65px;
        padding-bottom: 15px;
        margin-bottom: 13vh;
    }

    .detail-item {
        text-align: center;
        margin: 1rem;

    }

    .footer {
        position: relative;
        height: 25px;
        background-color: black;
        text-align: center;
        color: white;
        bottom: 0px;
        left: 0px;
        right: 0px;
        margin-bottom: 0px;
        margin-top: 10px;
    }


    @media only screen and (max-width: 600px) {
        .search__input {
            display: none;
        }

        .navbar-brand {
            display: none;
        }

        .username {
            display: none;
        }

        .inmobile {
            display: block;
        }
    }

    @media only screen and (min-width: 600px) {
        .inmobile {
            display: none;
        }

        .name {
            display: none;

        }

        .container-userimage {
            left: 43.5%;
            margin-top: 70px;
        }
    }
</style>
{% endblock %}


{% block content %}

<header class="sticky-top" style="z-index: 0;">
    <nav class="navbar">
        <div class="container">

            <a class="navbar-brand inmobile" href="/">
                <img src="{% static 'img/techblogonlylogo.png' %}" class="nav__logo"
                    style="height: 2.5rem; width: 2.5rem;">
            </a>

            <a href="{% url 'blog:blog_view' user.username %}" style="font-size: 2rem; padding-bottom: 20px;"
                class="username">
                <b>{{ user.username }}</b>
            </a>

            <a href="{% url 'blog:profile_view' user.username %}">
                About
            </a>

            <div class="search__input m-auto d-none d-md-block">

                <!-- Form to search Users -->
                <form method="GET" action="" class="form-inline">
                    <input type="text" autocomplete="on" placeholder="Search Blog" value="" class="searchspace"
                        name="query">
                    <button type="submit" class="ml-2 btn p-0">
                        <i class="fa fa-search"></i>
                    </button>
                </form>
                <!-- Form to search Users End -->

            </div>

            <ul class="navbar-nav ml-0 ml-md-auto d-flex flex-row" style="cursor: pointer;">

                <!-- Dropdown for more menu -->
                <li class="nav-item dropdown ml-2">
                    <a class="nav-link dropdown-toggle" id="user__avatar" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false" style="padding-top: inherit;padding: inherit;">


                        {% if user.picture_url %}
                        <img src="{{ user.picture_url }}" class="rounded-circle z-depth-0">
                        {% else %}
                        <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"
                            class="rounded-circle z-depth-0">
                        {% endif %}

                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user__avatar">

                        <a class="dropdown-item" href="{% url 'blog:profile_view' request.user.username %}">
                            <span class="mr-3 fa fa-user-circle"></span>Profile
                        </a>

                        <a class="dropdown-item" href="{% url 'blog:profile_edit_view' request.user.username %}">
                            <span class="mr-3 fa fa-user-circle"></span>Edit Profile
                        </a>

                        <a class="dropdown-item" href="">
                            <span class="mr-3 fa fa-cog"></span>Change Password
                        </a>

                        <div class="dropdown-divider"></div>

                        <div class="dropdown-item">
                            <form method="POST" action="{% url 'blog:signout' %}">
                                {% csrf_token %}
                                <a href="javascript:;" onclick="parentNode.submit();"
                                    class="text-reset text-decoration-none">Sign
                                    Out</a>
                            </form>
                        </div>
                    </div>
                </li>

            </ul>

            <a class="navbar-brand" href="/">
                <img src="{% static 'geek_logo.png' %}" class="nav__logo" style="width: 5rem; height: 3rem;">
            </a>

        </div>
    </nav>
</header>

<div class="content" style="height: 55vh;">

</div>

{% endblock %}

Techblog/templates/authentication/auth_user.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block extra_head %}

<link href="{% static 'img/user-profile-avtr-2.png' %}" rel="icon" />
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}" />
<title>Home | {{ request.user.username }}</title>
<style>
    #user__avatar img {
        height: 26px;
        width: 26px;
    }

    .navbar-nav .dropdown-menu {
        position: absolute !important;
    }

    .nav__icons {
        font-size: 24px;
    }

    .signout__btn {
        border: none;
        background: none;
        cursor: pointer;
        padding: 0;
        text-decoration: none;
    }

    .container a {
        text-decoration: none;
        padding: 10px;
    }

    header {
        box-shadow: 0 0 3px 0.5px black;
        background-color: rgba(248, 35, 35, 0.789);
    }

    .searchspace {
        border: none;
        font-size: medium;
        width: 110px;
        height: 25px;
        padding: 10px;
        margin: 10px;
        background-color: rgba(251, 43, 43, 0.716);
        color: white;
        border-bottom: 2px solid white;
        outline: none;
    }

    .name {
        margin-top: 2rem;
        margin-left: 1.5rem;
        text-align: center;
    }

    a {
        text-decoration: none;
    }

    .container-userimage {
        width: 200px;
        height: 200px;
        margin: auto;
    }

    .container-userimage>img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .detail-container {
        display: flex;
        width: 80vw;
        box-shadow: 0 0 5px 3px black;
        flex-direction: column;
        border-radius: 20px;
        padding-top: 65px;
        padding-bottom: 15px;
        margin: auto;
        margin-top: -9vh;
        margin-bottom: 13vh;
    }

    .detail-item {
        text-align: center;
        margin: 1rem;
    }

    .footer {
        position: relative;
        height: 25px;
        background-color: black;
        text-align: center;
        color: white;
        bottom: 0px;
        left: 0px;
        right: 0px;
        margin-bottom: 0px;
        margin-top: 10px;
    }

    @media only screen and (max-width: 600px) {
        .search__input {
            display: none;
        }

        .navbar-brand {
            display: none;
        }

        .username {
            display: none;
        }

        .inmobile {
            display: block;
        }
    }

    @media only screen and (min-width: 600px) {
        .inmobile {
            display: none;
        }

        .name {
            display: none;
        }

        .container-userimage {
            left: 27%;
            margin-top: 7rem;
        }
    }
</style>

{% endblock %}

{% block content %}

<header class="sticky-top" style="z-index: 5">
    <nav class="navbar">
        <div class="container">
            <a class="navbar-brand inmobile" href="/">
                <img src="{% static 'img/techblogonlylogo.png' %}" class="nav__logo"
                    style="height: 2.5rem; width: 2.5rem" />
            </a>

            <a href="{% url 'blog:blog_view' user.username %}" style="font-size: 2rem; padding-bottom: 20px"
                class="username">
                <b>{{ user.username }}</b>
            </a>

            <a href="{% url 'blog:profile_view' user.username %}"> About </a>

            <div class="search__input m-auto d-none d-md-block">
                <!-- Form to search Users -->
                <form method="GET" action="" class="form-inline">
                    <input type="text" autocomplete="on" placeholder="Search Blog" value="" class="searchspace"
                        name="query" />
                    <button type="submit" class="ml-2 btn p-0">
                        <i class="fa fa-search"></i>
                    </button>
                </form>
                <!-- Form to search Users End -->
            </div>

            <ul class="navbar-nav ml-0 ml-md-auto d-flex flex-row" style="cursor: pointer">
                <!-- Dropdown for more menu -->
                <li class="nav-item dropdown ml-2">
                    <a class="nav-link dropdown-toggle" id="user__avatar" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false" style="padding-top: inherit; padding: inherit">
                        {% if user.picture_url %}
                        <img src="{{ user.picture_url }}" class="rounded-circle z-depth-0" />
                        {% else %}
                        <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"
                            class="rounded-circle z-depth-0" />
                        {% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user__avatar">
                        <a class="dropdown-item" href="{% url 'blog:profile_view' request.user.username %}">
                            <span class="mr-3 fa fa-user-circle"></span>Profile
                        </a>

                        <a class="dropdown-item" href="{% url 'blog:profile_edit_view' request.user.username %}">
                            <span class="mr-3 fa fa-user-circle"></span>Edit Profile
                        </a>

                        <a class="dropdown-item" href="">
                            <span class="mr-3 fa fa-cog"></span>Change Password
                        </a>

                        <div class="dropdown-divider"></div>

                        <div class="dropdown-item">
                            <form method="POST" action="{% url 'blog:signout' %}">
                                {% csrf_token %}
                                <a href="javascript:;" onclick="parentNode.submit();"
                                    class="text-reset text-decoration-none">Sign
                                    Out</a>
                            </form>
                        </div>
                    </div>
                </li>

            </ul>

            <a class="navbar-brand" href="/">
                <img src="{% static 'geek_logo.png' %}" class="nav__logo" style="width: 5rem; height: 3rem" />
            </a>
        </div>
    </nav>
</header>


<div class="name">
    <p>
        <span style="font-size: 2rem"><b>{{ user.full_name }}</b></span>
    </p>
    <p>
        <a href=""><span>4 Follower </span></a>
        <a href=""><span> 3 Following </span></a>
    </p>
</div>

<div class="container-userimage">
    {% if user.picture_url %}
    <img src="{{ user.picture_url }}" class="rounded-circle z-depth-0" />
    {% else %}
    <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"
        class="rounded-circle z-depth-0" />
    {% endif %}
</div>

<div class="detail-container">
    <div class="detail-item">{{request.user.full_name}}</div>
    <div class="detail-item">{{request.user.email}}</div>
    <div class="detail-item">{{request.user.college}}</div>
    <div class="detail-item">{{request.user.status}}</div>
    <div class="detail-item">{{request.user.website}}</div>
    <div class="detail-item">{{request.user.phone_number}}</div>
    <div class="detail-item">{{request.user.country}}</div>
    <div class="detail-item">{{request.user.gender}}</div>
</div>
{% endblock %}

Techblog/templates/authentication/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="theme-color" content="#000000" />
  <meta name="mobile-web-app-capable" content="yes" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous" />
  {% block extra_head %} {% endblock %}
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
    integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous" />
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet" />

  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <style>
    /* * {
			padding: 0;
			margin: 0;
			box-sizing: border-box;
		} */
    button {
      height: 60px;
      width: 60px;
      background-color: rgba(0, 0, 0, 0.795);
      border: none;
      cursor: pointer;
      border-radius: 5px;

    }

    #dialogflow {

      position: fixed;
      left: 73%;
      bottom: 15%;
      border: 2px solid black;
      background-color: black;
      border-radius: 5px;
      display: none;
      z-index: 10;
    }

    #togglebutton {
      position: fixed;
      left: 92%;
      bottom: 5%;
      border-radius: 5px;
      z-index: 10;
    }

    #togglebutton:hover {
      background-color: #000;
    }

    @media only screen and (max-width: 600px) {
      #togglebutton {
        left: 82%;
      }
    }

    #div1 {
      background-color: #8888ff;
      display: block;
      height: 0px;
      overflow: hidden;
      border: 1px solid #000;
    }

    .footer {
      position: relative;
      height: 165px;
      background-color: rgb(18, 17, 17);
      text-align: center;
      color: white;
      bottom: 0px;
      left: 0px;
      right: 0px;
      margin-bottom: 0px;
      margin-top: 10px;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#" style="color: white">geekENV</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:index_view' %}"
              style="color: white">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:createblog' %}" style="color: white">Publish</a>
          </li>
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:signup' %}" style="color: white">Get Started</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ide:ideurl' %}" style="color: white">Compile and Run</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
              data-bs-toggle="dropdown" aria-expanded="false" style="color: white">
              More
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li>
                <a class="dropdown-item" href="{% url 'blog:about' %}">About</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'blog:contact' %}">Contact Us</a>
              </li>
              {% if request.user.is_authenticated %}
              <li>
                <a class="dropdown-item" href="{% url 'blog:signout' %}">Logout</a>
              </li>
              {% endif %}
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="dialogflow">
    <iframe id="frame" allow="microphone;" width="350"
      src="https://console.dialogflow.com/api-client/demo/embedded/f820f653-1eb7-4940-9294-0c7ac2373638">
    </iframe>

  </div>
  <div id="togglebutton">
    <button onclick="bottoggle()">
      <i class="material-icons" style="color: #f35d27;font-size:35px; margin-top: 5px;"><span
          id="toggletext">chat_bubble</span></i>
    </button>
  </div>

  {% block content %} {% endblock %}

  <div class="footer">
    <h5>All rights reserved<br>geekENV Inc©</h5>
    <div><a href="#">Home</a><a href="#">About</a><a href="#">Publish</a><a href="#">Contact</a></div>
    <div>
      <i class="fab fa-facebook-f fa-2x" style="margin:10px"></i>
      <i class="fas fa-envelope fa-2x" style="margin:10px"></i>
      <i class="fab fa-github fa-2x" style="margin:10px"></i>
      <i class="fab fa-twitter fa-2x" style="margin:10px"></i>
    </div>

    Made with <i class="fas fa-heart"></i> in India
  </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>


</body>
<script>
  function bottoggle() {
    var x = document.getElementById("dialogflow");
    var y = document.getElementById("toggletext");
    var frameD = document.getElementById("frame");

    if (x.style.display == "block") {
      y.innerHTML = "chat_bubble";

      x.style.display = "none";
      x.style.color = "#f35d27";

      frameD.style.height = 0;

    }
    else {
      y.innerHTML = "power_settings_new";

      x.style.display = "block";
      x.style.color = "red";

      frameD.style.height = "550px";

    }
  }

</script>

</html>

Techblog/templates/authentication/register_s.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block extra_head %}

<title> User Registration</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/Register_extend.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/signup.css' %}">

{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto signup__card">
                <img src="{% static 'img_signup.png' %}" class="insta__logo mt-4 mb-3 mx-auto">
                <div class="signup">
                    <p class="signup__card__text">Sign up to see Tech related Blog and IDE.</p>
                    <!-- <div class="my-4 mx-auto text-center">
                        <button class="btn btn-sm auth__btn">Log in with Facebook</button>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div> -->
                    <div>
                        {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.non_field_errors }}
                        </div>
                        {% endif%}
                    </div>
                    <div class="signup__form mb-3">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="my-1 form__input">
                                <input id="id_email" type="email" name="email" placeholder="Email"
                                    class="form-control {% if form.email.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.email.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_username" type="text" name="username" placeholder="Username"
                                    class="form-control {% if form.username.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.username.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_full_name" type="text" name="full_name" placeholder="Full Name"
                                    class="form-control {% if form.full_name.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.full_name.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_password1" type="password" name="password1" placeholder="Password"
                                    class="form-control {% if form.password1.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.password1.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_password2" type="password" name="password2" placeholder="Retype Password"
                                    class="form-control {% if form.password2.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.password2.errors }}
                                </div>
                            </div>
                            <div class="my-4 mx-auto text-center">
                                <button class="btn btn-sm auth__btn" type="submit">Sign up</button>
                            </div>
                        </form>
                    </div>
                    <p class="terms__conditions mb-4">By signing up, you agree to our <strong>Terms</strong> ,
                        <strong>Data Policy</strong> and <strong>Cookies Policy</strong> .
                    </p>
                </div>
            </div>
            <div class="text-center card mt-2 px-5 mx-auto signup__card">
                <p class="have__an__account py-3">Have an account? <a href="{% url 'blog:signin' %}"
                        class="text-decoration-none">Sign in</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}